#!/usr/bin/env node

var execlib = require('..');


execlib.loadDependencies('client', ['allex:master'], run);

function run () {
  execlib.execSuite.taskRegistry.run('findMasterPid', {
    cb: go
  });
}

function go (pid) {
  execlib.execSuite.taskRegistry.run('findAndRun', {
    masterpid: pid,
    program: {
      sinkname: execlib.execSuite.sinkNameFromString(process.argv[2]),
      identity: {name: 'user', role: 'user'},
      task: {
        name: doForcePassword
      }
    }
  });
}

function doForcePassword (taskobj) {
  console.log('doForcePassword');
  if (!(taskobj && taskobj.sink)) {
    console.error('sink could not be found for', process.argv[2]);
    return;
  }
  execlib.lib.qlib.promise2console(taskobj.sink.call('forcePassword', process.argv[3], process.argv[4]), 'forcePassword for '+process.argv[3]+' with password '+process.argv[4]).then(
    process.exit.bind(process, 0),
    process.exit.bind(process, 1)
  );
}
